#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "HyperTwistSimulation/HyperTwistSimulationTypes.h"
#include "HyperTwistSimulationLibrary.generated.h"

UCLASS()
class UNREALHYPERTWIST_API UHyperTwistSimulationLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category = "HyperTwist|Simulation")
	static FHyperTwistSimulationSceneContext MakeClassicPlaceholderSceneContext();

	UFUNCTION(BlueprintPure, Category = "HyperTwist|Simulation")
	static FHyperTwistSimulationSceneContext MakeHyperPlaceholderSceneContext();

	UFUNCTION(BlueprintPure, Category = "HyperTwist|Simulation")
	static bool CanRenderSceneContext(const FHyperTwistSimulationSceneContext& SceneContext);
};
