#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "HyperTwistReplay/HyperTwistReplayTypes.h"
#include "HyperTwistReplayLibrary.generated.h"

UCLASS()
class UNREALHYPERTWIST_API UHyperTwistReplayLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category = "HyperTwist|Replay")
	static FHyperTwistReplayPacket AppendReplayEvent(const FHyperTwistReplayPacket& Packet, const FHyperTwistReplayEvent& Event);

	UFUNCTION(BlueprintPure, Category = "HyperTwist|Replay")
	static FHyperTwistDerivedReplaySummary DeriveReplaySummary(const FHyperTwistReplayPacket& Packet);
};
